---
- hosts: localhost
  become: sudo
  user: vos
  connection: ssh
  
# TODO: adduser


  tasks:
    - name: install packages
      apt: name={{ item }} state=latest
      with_items:
        - htop
        - git
        - subversion
        - zsh
        - vim
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
      register: installation

    - name: install packages 
      yum: name={{ item }} state=latest
      with_items:
        - zsh
        - git
        - subversion
        - htop
        - vim
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
      register: installation

    - name: Backing up existing ~/.zshrc
      shell: if [ -f ~/.zshrc ]; then mv ~/.zshrc{,.orig}; fi
      when: installation|success
      sudo: no

    - name: Cloning oh-my-zsh
      git:
        repo=https://github.com/robbyrussell/oh-my-zsh
        dest=~/.oh-my-zsh
      when: installation|success
      register: cloning
      sudo: no

    - name: Creating new ~/.zshrc
      copy:
        src=~/.oh-my-zsh/templates/zshrc.zsh-template
        dest=~/.zshrc
      when: cloning|success
      sudo: no

